### PR TITLE
Upgrade dependency versions, remove legacy dependencies and fix travis build errors

### PR DESCRIPTION
**Pull request by halfvim**
* upgrade dependency versions
  * upgraded spark version from 2.3.1 to 2.4.4, to conform with the latest version of EMR. We should keep spark version with the latest.
  * upgraded scala version to 2.11.12
  * upgraded other dependencies to latest
* cleanup legacy dependencies
  * removed `commons-lang3`, as it's not in use
  * removed `commons-codec`, as it's not in use; and the `1.11` version is conflicting with hadoop library dependencies latest EMR version is using. The comment in our pom.xml says "Used for base-64 encoding for HTTP basic authentication (which we need to access Jenkins)" for this dependency, but I did not find such a usage.
* travis build errors
  * there were jdk version compatibility issue, added jdk version in travis yml file.

### CODE REVIEW

**Comment by wnilkamal** [comment]
## Migration Recommended

It appears you are still using the CoPilot OAuth App - we recommend you [migrate to the GitHub App](https://github.com/apps/blackduck-copilot/installations/new/permissions?suggested_target_id=5703372&repository_ids[]=113910466&repository_ids[]=53422857&repository_ids[]=137085185&repository_ids[]=14179154)

**Comment by wnilkamal** [comment]
## Migration Recommended

It appears you are still using the CoPilot OAuth App - we recommend you [migrate to the GitHub App](https://github.com/apps/blackduck-copilot/installations/new/permissions?suggested_target_id=5703372&repository_ids[]=113910466&repository_ids[]=53422857&repository_ids[]=137085185&repository_ids[]=14179154)

**Comment by halfvim** [comment]
> ## Migration Recommended
> It appears you are still using the CoPilot OAuth App - we recommend you [migrate to the GitHub App](https://github.com/apps/blackduck-copilot/installations/new/permissions?suggested_target_id=5703372&repository_ids%5B%5D=113910466&repository_ids%5B%5D=53422857&repository_ids%5B%5D=137085185&repository_ids%5B%5D=14179154)

how do i do that?

**Comment by matthewgillett** [comment]
Closing and reopening pull request to re-trigger checks.

**Pull request merged**
